[package]
name = "qpak"
description = "Unofficial Quake PAK file manipulation tool"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories = [
    "command-line-utilities",
    "filesystem",
    "game-development",
    "parsing",
]

[dependencies]
qpak-lib.workspace = true
clap = { version = "4.5.30", features = ["derive"] }
tempfile = "3.17.1"

[dev-dependencies]
dir-diff = "0.3.3"
